# Generated by Django 3.1.4 on 2021-07-18 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210718_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('D', 'Delivered'), ('PO', 'Processing'), ('S', 'Shipping')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 15, 33, 16, 775668)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 15, 33, 16, 776664)),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 15, 33, 16, 776664)),
        ),
    ]
