# Generated by Django 3.1.4 on 2021-07-18 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210718_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 15, 34, 1, 506514)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 15, 34, 1, 506514)),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 15, 34, 1, 507507)),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
